### ISSUE TITLE
U+33C7 SQUARE CO が "Ca" になっている

### ISSUE THREAD

**Issue by lo48576** [daisukesuzuki/VLGothic#1]
![2023-10-05-072341+0900](https://github.com/daisukesuzuki/VLGothic/assets/1246590/7156de84-a148-469c-a2b1-037ecb040a9f)

U+33C7 SQUARE CO (㏇) は "Co." のような形で描画されるべきですが、 VL Pゴシックと VL ゴシックいずれも "Ca" になっています。

**Comment by daisukesuzuki** [comment]
ご指摘ありがとうございます。
dbaac2843ae55e333df69330b8d13a0c7fb507bd で修正しました
